### ISSUE TITLE
Update `pages` and `requests` schemas on staging to match crawl dataset

### ISSUE THREAD

**Issue by max-ostapenko** [HTTPArchive/wptagent#18]
The older data schema is being reprocessed using these queries:
- [pages.js](https://github.com/HTTPArchive/dataform/blob/main/definitions/output/crawl/pages.js)
- [requests.js](https://github.com/HTTPArchive/dataform/blob/main/definitions/extra/migration/reprocess_requests.js)

After we promote these new schemas to be the new default we need to update agent processing.

We should be able to just do `SELECT *` when copying data from `crawl_staging` to `crawl` in crawl_complete pipeline.

**Comment by max-ostapenko** [comment]
The transformation of `crawl_staging.requests` into `crawl.requests` lasted ~13h for Nov 2024 crawl (not including failed attempts).

@pmeenan let's update the wptagent to match `crawl_staging` with `crawl` schema.
As agreed we will not update legacy table anymore, so ready for a cleanup.

**Comment by max-ostapenko** [comment]
I hope it's not gonna be needed, BUT in case there are some issues with [ingesting data to JSON columns](https://cloud.google.com/bigquery/docs/json-data#ingest_json_data) we can fallback to parsing STRING data within the pipeline as we do currently.

**Comment by max-ostapenko** [comment]
@pmeenan from data in crawl_staging it looks like `pages.summary` values are not yet trimmed, e.g.:
- '$._adult_site',
- '$.archive',
- '$.avg_dom_depth',
- '$.crawlid',
- '$.createDate',
- '$.doctype',
- '$.document_height',
- '$.document_width',
- '$.label',
- '$.localstorage_size',
- '$.meta_viewport',
- '$.metadata',
- '$.num_iframes',
- '$.num_scripts_async',
- '$.num_scripts_sync',
- '$.num_scripts',
- '$.pageid',
- '$.PageSpeed',
- '$.rank',
- '$.sessionstorage_size',
- '$.startedDateTime',
- '$.url',
- '$.urlhash',
- '$.urlShort',
- '$.usertiming',
- '$.wptid',
- '$.wptrun'

and `pages.metadata`:

- '$.page_id',
- '$.parent_page_id',
- '$.root_page_id'

True, or are these rows outdated?

**Comment by max-ostapenko** [comment]
Some of these fields were removed in https://github.com/HTTPArchive/wptagent/pull/15.
How should we proceed?

**Comment by pmeenan** [comment]
Were they present in all the records? The first few were before I removed
the fields but the last 1-2 should have most of them removed.

**Comment by max-ostapenko** [comment]
Yeah, if sorted by `payload.startedDateTime` last two are OK. 
👍🏽
