### ISSUE TITLE
Should JSON be "script" type?

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/wptagent#19]
JSON currently have a type of `script`

https://github.com/HTTPArchive/wptagent/blob/6f925bb1e054f0e01c86215ab3895b8d6ae0f8f1/HTTPArchive/utils.py#L57-L59

`script`s are most of the requests so querying for JSON is quite expensive.

Should we split this out to it's own `json` type? Or is there a reason it should be `script`?

**Comment by pmeenan** [comment]
Out as its own type works for me. I'm pretty sure that's just something Steve did way back in the day. I expect it would only cause a rounding error to the number of scripts on a page metrics.
